#!/usr/bin/env python3
"""Generate src/unicode_tables.inc: the Unicode data the tokenizer needs (ADR_002 D10).

  - general-category ranges for Letter (L*), Mark (M*) and Number (N*), for the pre-tokeniser regex;
  - canonical combining classes, full canonical decompositions and primary compositions, for NFC.

Source: the `unicodedata2` package pinned in tools/requirements.txt (Unicode version recorded in
the output). Usage: .venv/bin/python tools/gen_unicode_tables.py > src/unicode_tables.inc
"""
import sys

import unicodedata2 as ud

MAX = 0x110000
HANGUL_S0, HANGUL_S1 = 0xAC00, 0xD7A3


def category_ranges():
    flag = {"L": 1, "M": 2, "N": 4}
    ranges, cur = [], None
    for cp in range(MAX):
        f = flag.get(ud.category(chr(cp))[0], 0)
        if cur and cur[2] == f and cur[1] == cp - 1:
            cur[1] = cp
        else:
            if cur and cur[2]:
                ranges.append(tuple(cur))
            cur = [cp, cp, f]
    if cur and cur[2]:
        ranges.append(tuple(cur))
    return ranges


def full_decomposition(cp):
    d = ud.decomposition(chr(cp))
    if not d or d.startswith("<"):
        return [cp]
    out = []
    for part in d.split():
        out += full_decomposition(int(part, 16))
    return out


def main():
    out = sys.stdout
    out.write("// Generated by tools/gen_unicode_tables.py from unicodedata2 (Unicode %s). Do not edit.\n"
              % ud.unidata_version)
    out.write("// clang-format off\n")

    rs = category_ranges()
    out.write("constexpr CategoryRange kCategoryRanges[] = {\n")
    for lo, hi, f in rs:
        out.write("{0x%X,0x%X,%d},\n" % (lo, hi, f))
    out.write("};\n")

    ccc = [(cp, ud.combining(chr(cp))) for cp in range(MAX) if ud.combining(chr(cp))]
    out.write("constexpr CombiningClass kCombiningClasses[] = {\n")
    for cp, c in ccc:
        out.write("{0x%X,%d},\n" % (cp, c))
    out.write("};\n")

    decomp, data = [], []
    for cp in range(MAX):
        if HANGUL_S0 <= cp <= HANGUL_S1:
            continue  # algorithmic
        d = full_decomposition(cp)
        if d != [cp]:
            decomp.append((cp, len(data), len(d)))
            data += d
    out.write("constexpr char32_t kDecompositionData[] = {\n")
    for i in range(0, len(data), 12):
        out.write(",".join("0x%X" % c for c in data[i:i + 12]) + ",\n")
    out.write("};\n")
    out.write("constexpr Decomposition kDecompositions[] = {\n")
    for cp, off, n in decomp:
        out.write("{0x%X,%d,%d},\n" % (cp, off, n))
    out.write("};\n")

    # Primary composites: canonical pair decompositions that NFC recomposes (excludes composition
    # exclusions and singletons).
    comp = []
    for cp in range(MAX):
        if HANGUL_S0 <= cp <= HANGUL_S1:
            continue
        d = ud.decomposition(chr(cp))
        if not d or d.startswith("<"):
            continue
        parts = [int(p, 16) for p in d.split()]
        if len(parts) == 2 and ud.normalize("NFC", chr(parts[0]) + chr(parts[1])) == chr(cp):
            comp.append((parts[0], parts[1], cp))
    comp.sort()
    out.write("constexpr Composition kCompositions[] = {\n")
    for a, b, c in comp:
        out.write("{0x%X,0x%X,0x%X},\n" % (a, b, c))
    out.write("};\n")
    out.write("// clang-format on\n")


if __name__ == "__main__":
    main()
